// Mocks generated by Mockito 5.4.4 from annotations
// in mokitotest/test/cat_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:mokitotest/cat.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDog_0 extends _i1.SmartFake implements _i2.Dog {
  _FakeDog_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Cat].
///
/// See the documentation for Mockito's code generation for more information.
class MockCat extends _i1.Mock implements _i2.Cat {
  @override
  _i2.Dog get dog => (super.noSuchMethod(
        Invocation.getter(#dog),
        returnValue: _FakeDog_0(
          this,
          Invocation.getter(#dog),
        ),
        returnValueForMissingStub: _FakeDog_0(
          this,
          Invocation.getter(#dog),
        ),
      ) as _i2.Dog);

  @override
  set dog(_i2.Dog? _dog) => super.noSuchMethod(
        Invocation.setter(
          #dog,
          _dog,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get lives => (super.noSuchMethod(
        Invocation.getter(#lives),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set lives(int? _lives) => super.noSuchMethod(
        Invocation.setter(
          #lives,
          _lives,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String sound() => (super.noSuchMethod(
        Invocation.method(
          #sound,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #sound,
            [],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #sound,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<String> getType(String? color) => (super.noSuchMethod(
        Invocation.method(
          #getType,
          [color],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getType,
            [color],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getType,
            [color],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> getLoai(String? color) => (super.noSuchMethod(
        Invocation.method(
          #getLoai,
          [color],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getLoai,
            [color],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getLoai,
            [color],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  bool eatFood(
    String? food, {
    bool? hungry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #eatFood,
          [food],
          {#hungry: hungry},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> chew() => (super.noSuchMethod(
        Invocation.method(
          #chew,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int walk(List<String>? places) => (super.noSuchMethod(
        Invocation.method(
          #walk,
          [places],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void sleep() => super.noSuchMethod(
        Invocation.method(
          #sleep,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hunt(
    String? place,
    String? prey,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #hunt,
          [
            place,
            prey,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Dog].
///
/// See the documentation for Mockito's code generation for more information.
class MockDog extends _i1.Mock implements _i2.Dog {
  @override
  int get lives => (super.noSuchMethod(
        Invocation.getter(#lives),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set lives(int? _lives) => super.noSuchMethod(
        Invocation.setter(
          #lives,
          _lives,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String sound() => (super.noSuchMethod(
        Invocation.method(
          #sound,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #sound,
            [],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #sound,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<String> getType(String? color) => (super.noSuchMethod(
        Invocation.method(
          #getType,
          [color],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getType,
            [color],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getType,
            [color],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> getLoai(String? color) => (super.noSuchMethod(
        Invocation.method(
          #getLoai,
          [color],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getLoai,
            [color],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getLoai,
            [color],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  bool eatFood(
    String? food, {
    bool? hungry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #eatFood,
          [food],
          {#hungry: hungry},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> chew() => (super.noSuchMethod(
        Invocation.method(
          #chew,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int walk(List<String>? places) => (super.noSuchMethod(
        Invocation.method(
          #walk,
          [places],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void sleep() => super.noSuchMethod(
        Invocation.method(
          #sleep,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hunt(
    String? place,
    String? prey,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #hunt,
          [
            place,
            prey,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
